SELECT e.NAME AS EMPLOYEE, e.SALARY, d.NAME AS DEPARTMENT
FROM EMPLOYEE e
JOIN DEPARTMENT d ON e.DEPARTMENTID = d.ID
WHERE (e.DEPARTMENTID, e.SALARY) IN (
  SELECT DEPARTMENTID, MAX(SALARY)
  FROM EMPLOYEE
  GROUP BY DEPARTMENTID
)
ORDER BY e.SALARY DESC;