# Write your MySQL query statement below
SELECT 
    CASE 
        WHEN COUNT(DISTINCT SALARY) >= 2 THEN
        (SELECT DISTINCT SALARY FROM EMPLOYEE ORDER BY SALARY DESC LIMIT 1 OFFSET 1)
        ELSE NULL
    END AS SECONDHIGHESTSALARY
FROM EMPLOYEE; 